### ISSUE TITLE
Не указывать published: true в модели

### ISSUE THREAD

**Issue by vithar** [bem-site/gorshochek#30]
"published": true надо сделать значением по умолчанию и не использовать его для каждой страницы в модели. А вот "published": false указывать.

**Comment by tormozz48** [comment]
Проверил, что логика горшочка подразумевает `published: true` в случае, когда поле `published` не указано. Удалил из модели bem.info вот в этом коммите https://github.com/vithar/bem.info/commit/e82a1afff17c31cdcc73848a02807cdc7ab6f204
