### ISSUE TITLE
В .gorshochek/data-* весь русский текст в виде entity

### ISSUE THREAD

**Issue by vithar** [bem-site/gorshochek#31]
В сгенерированных `.html` из `.md` весь русский текст в виде html-entity (&#x42D;&#x43B;&#x435;&#x43C;&#x435;&#x43D;&#x442;), а не буквами.

Скорее всего где-то не указана utf8, как результирующая кодировка.

**Comment by vithar** [comment]
@tormozz48 И да, добавь меня в контрибьюторы, чтобы я мог вешать labels и менять assignee.

**Comment by tormozz48** [comment]
Выяснил, что это делает модуль  [cheerio](https://www.npmjs.com/package/cheerio), который используется для разбора html в модулях переопределения ссылок и изображений

**Comment by tadatuta** [comment]
переходи на светлую сторону парсеров, типа https://www.npmjs.com/package/htmlparser2, не создающих DOM — это как минимум быстрее.

**Comment by tormozz48** [comment]
> переходи на светлую сторону парсеров, типа https://www.npmjs.com/package/htmlparser2, не создающих DOM — это как минимум быстрее.

Ты учти, что мне нужно разобрать дом, пройти по всем нужным элементам, заменить значения атрибутов и снова сохранить измененный html.

Вообще если говорить про скорость, то здесь выиграет обычный .replace() с регулярками

**Comment by tormozz48** [comment]
Пока решил проблему с помощью https://lodash.com/docs#unescape

**Comment by tormozz48** [comment]
Исправлено в версии v2.1.2

**Comment by vithar** [comment]
Вообще я не очень понимаю, почему ты делаешь отдельные проходы по всему html, а не делаешь это во время вывода из md через функцию рендерера для ссылок.
